---
- name: Include variables from meta/main.yml
  include_vars:
    file: "{{ generator_role_path }}/meta/main.yml"
    name: meta

- name: Generate molecule files | Create Necessary Dirs
  file:
    path: "{{ generator_role_path }}/molecule/{{ item.name }}"
    state: directory
  loop: "{{ generator_molecule_scenarios + [ {'name': 'default'} ] }}"

- name: Create other necessary directories
  when:
    - generator_dirs is defined
    - generator_dirs is iterable
  loop: "{{ generator_dirs }}"
  file:
    path: "{{ item }}"
    state: directory

- name: Copy default files
  when:
    - generator_files is defined
    - generator_files is iterable
  block:
    - name: Copy default files | Copy file if needed
      loop: "{{ generator_files }}"
      loop_control:
        label: "{{ item['dest'] }}"
      when:
        - (item['state'] is undefined) or (item['state'] in [ "present", "force" ])
      template:
        src: "{{ item['src'] | default('defaults/' ~ item['dest'] ~ '.j2') }}"
        dest: "{{ generator_role_path }}/{{ item['dest'] }}"

    - name: Copy default files | Delete files if needed
      loop: "{{ generator_files }}"
      when: item['state'] is defined and item['state'] == "absent"
      file:
        path: "{{ generator_role_path }}/{{ item['dest'] }}"
        state: absent

- name: Check if requirements.yml is present
  register: requirements_stat
  stat:
    path: "{{ generator_role_path }}/requirements.yml"

- name: Generate molecule files | Check if default molecule.yml is present
  register: default_molecule_yml_stat
  stat:
    path: "{{ generator_role_path }}/molecule/default/molecule.yml"

- name: Generate molecule files | Check if prepare.yml is present
  register: prepare_stat
  stat:
    path: "{{ generator_role_path }}/molecule/default/prepare.yml"

- name: Generate molecule files | Check if converge.yml is present
  register: converge_stat
  stat:
    path: "{{ generator_role_path }}/molecule/default/converge.yml"

- name: Generate molecule files | Check if verify.yml is present
  register: verify_stat
  stat:
    path: "{{ generator_role_path }}/molecule/default/verify.yml"

- name: Generate molecule files | Create molecule.yml files
  template:
    src: "molecule/{{ molecule_file.format }}/molecule.yml.j2"
    dest: "{{ generator_role_path }}/molecule/{{ molecule_file.name }}/molecule.yml"
  loop_control:
    loop_var: molecule_file
  loop: "{{ generator_molecule_scenarios }}"

- name: Generate molecule files | Link default molecule.yml if not present
  file:
    state: link
    src: "{{ generator_role_path }}/molecule/{{ generator_molecule_default_scenario }}/molecule.yml"
    dest: "{{ generator_role_path }}/molecule/default/molecule.yml"

- name: Generate molecule files | Link prepare.yml if present
  when: prepare_stat.stat.exists | bool
  loop: "{{ generator_molecule_scenarios }}"
  file:
    state: link
    src: "{{ generator_role_path }}/molecule/default/prepare.yml"
    dest: "{{ generator_role_path }}/molecule/{{ item.name }}/prepare.yml"

- name: Generate molecule files | Link converge.yml if present
  when: converge_stat.stat.exists | bool
  loop: "{{ generator_molecule_scenarios }}"
  file:
    state: link
    src: "{{ generator_role_path }}/molecule/default/converge.yml"
    dest: "{{ generator_role_path }}/molecule/{{ item.name }}/converge.yml"

- name: Generate molecule files | Link verify.yml if present
  when: verify_stat.stat.exists | bool
  loop: "{{ generator_molecule_scenarios }}"
  file:
    state: link
    src: "{{ generator_role_path }}/molecule/default/verify.yml"
    dest: "{{ generator_role_path }}/molecule/{{ item.name }}/verify.yml"
